### PR TITLE
feat: add a new linkify module

### PR DESCRIPTION
**Pull request by ahal**
I still plan to clean this up a bit and add better help text, but it seems to be working pretty much how I was hoping it would. A couple points:

1. I don't really care if this lives in Trinity core or not, I'm likely going to end up creating a separate module repository at some point anyway so lmk if you'd prefer it live elsewhere. Though I do wonder what your thoughts are on which modules should live directly in Trinity and which shouldn't.
2. I'm not sold on the name because it doesn't really linkify things, it's more of a general replace + reply module. Though I struggle to think of use cases that don't involve creating links..

### CODE REVIEW

**Comment by bnjbvr** [comment]
Sweet! Excited to try this out.

> Though I do wonder what your thoughts are on which modules should live directly in Trinity and which shouldn't.

I'm fine with having any module that seems useful to at least two different groups of people, or at least looks like it could be. Since I've been eagerly awaiting this one, I'm happy to have it in this repository, and help with the maintenance :grinning:

> Though I struggle to think of use cases that don't involve creating links..

We could rename it `search_replace` or `sar` (Search And Replace, although acronyms are less obvious), but as you point out, it seems to me that any use case that's more involved would better be implemented in a different module: templating (e.g. fill a string of the form `Uuid::from_str({UUID})` with a valid uuid, subsuming the `uuid` module), JS-like template string evaluation (e.g. run any self-contained code in a `javascript{ ... }` command).

**Comment by ahal** [comment]
Ah, didn't realize you were eagerly awaiting this or I may have worked on it sooner :). Feel free to take it past the finish line if you like, otherwise I'll try and wrap it up in the next week or two. I was just planning better help / error handling I think.

**Comment by ahal** [comment]
@bnjbvr this should be ready for review

**Comment by bnjbvr** [comment]
Sweet! I'll try to take a look in the next few days.

**Review by bnjbvr — APPROVED** [review]
Looks great, thanks! I've tweaked the code in place of doing a full review, mostly cosmetic changes and making the code a bit more idiomatic in a few places (feel free to take a look!).

So technically, one can remove a rule before it's been disabled, but it seems ok to "leak" the rule in that case, because that shouldn't happen often, and that won't cause issues the way the `replace` function is done (first get all the existing rules, then look if they belong to the enabled set in the current room). We could immediately fix that right now, by having the rule contain a backlink to all the rooms it's enabled in, if we wanted to solve that properly. There are other ways to fix that.

I don't consider this a blocker, and I'm fine taking the PR as is. It's just that, if we want to change the format of the data types stored in the KV database, it's more complicated to do it after the fact.

Thanks a lot for doing this! With this PR, trinity is really at feature parity with horsejs in terms of commands.

**Comment by bnjbvr** [comment]
(Also it's a brilliant idea to use markdown for the help, but unfortunately this isn't converted immediately in html form, something we can fix in followups)

**Comment by ahal** [comment]
Thanks for cleaning it up!

Yeah, there's that enable edge case as well as couple others I figured could be follow ups. I'll file some issues for them

**Comment by bnjbvr** [comment]
Alright, let's merge it now then! 🥳

**Pull request merged**
